FROM bettercode/scurl:latest as scurl
FROM centos:7 as runner
COPY --from=scurl /usr/local/bin/scurl /usr/local/bin/scurl
COPY . /s2erunner-src


RUN bash /s2erunner-src/os/centos/scripts/helpers/yum.sh
RUN bash /s2erunner-src/os/centos/scripts/helpers/basic.sh

ENV INSTALL_SCRIPTS=/s2erunner-src/os/centos/scripts/installers
ARG TCLIST="ansible.sh \
            cloud-aliyun-tencent-huawei-cli.sh \
            docker.sh \
            github-cli.sh \
            gitlab-cli.sh \
            gitlab-runner.sh \
            go.sh \
            image-magick.sh \
            java.sh \
            kubernetes-cli.sh \
            nodejs.sh"
# build time, runtime toolchains
RUN cd ${INSTALL_SCRIPTS}; \
 for s in ${TCLIST}; \
 do \
     set +e; \
     ls ${INSTALL_SCRIPTS}/$s >/dev/null 2>&1; \
     rv=$? ;\
     set -e; \
     if [ ${rv} -eq 0 ];then \
         echo "###${INSTALL_SCRIPTS}/$s"; \
         bash ${INSTALL_SCRIPTS}/validate-disk-space.sh; \
         set +e; bash ${INSTALL_SCRIPTS}/$s; ok=$?;set -e; \
         if [ ${ok} -ne 0 ];then echo $s >> /error.txt;fi \
     else \
         echo "*** not install $s"; \
     fi; \
 done;

COPY docker /docker

# cicd logic
RUN mv /s2erunner-src/s2e / ;\
    chmod -R +x /docker/ /s2e ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/gitlab-runner/config.toml     /etc/gitlab-runner/config.toml ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/profile.d/env.sh              /etc/profile.d/env.sh ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/maven/settings.xml            /root/.m2/settings.xml ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/docker/config.json            /root/.docker/config.json ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/k8s/                          /root/.kube ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/email/mail.rc                  /etc/mail.rc ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/jira/acli.properties           /root/jira/acli.properties ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/rancher/cli2.json              /root/.rancher/cli2.json ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/runner/secrets/s2ectl/config.yaml             /root/.s2ectl/config.yaml ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner/metricbeat/secrets/filebeat/filebeat.yml      /etc/filebeat/filebeat.yml ;\
    /bin/cp -rf /s2erunner-src/deployments/s2emetricd/secrets/elasticsearch/elasticsearch.yml      /etc/elasticsearch/elasticsearch.yml ;\
    /bin/cp -rf /s2erunner-src/deployments/s2emetricd/secrets/kibana/kibana.yml                    /etc/kibana/kibana.yml ;\
    /bin/cp -rf /s2erunner-src/deployments/s2emetricd/secrets/logstash                             /etc/logstash ;\
    /bin/cp -rf /s2erunner-src/deployments/s2emetricd/secrets/nginx/default.conf                   /etc/nginx/default.d/ ;\


RUN bash ${INSTALL_SCRIPTS}/cleanup.sh; \
 touch /error.txt; cat /error.txt; \
 yum clean all; \
 rm -rf /var/cache/yum; \
 rm -rf /root/ts;

ENTRYPOINT ["/docker/docker-entrypoint.sh"]
