FROM bettercode/scurl:latest as scurl
FROM ubuntu:18.04
COPY --from=scurl /usr/local/bin/scurl /usr/local/bin/scurl
COPY . /cicd-s2e-runner

ENV HELPER_SCRIPTS=/cicd-s2e-runner/os/ubuntu/scripts/helpers
ENV INSTALL_SCRIPTS=/cicd-s2e-runner/os/ubuntu/scripts/installers
ARG DEBIAN_FRONTEND=noninteractive
ARG METADATA_FILE=/cicd-s2e-runner/os/ubuntu/build.txt

RUN bash ${HELPER_SCRIPTS}/apt-init.sh

RUN bash /cicd-s2e-runner/os/ubuntu/scripts/helpers/apt.sh \
 && bash /cicd-s2e-runner/os/ubuntu/scripts/helpers/basic.sh \
 && bash /cicd-s2e-runner/os/ubuntu/scripts/helpers/limits.sh \
 && bash /cicd-s2e-runner/os/ubuntu/scripts/helpers/repos.sh


ARG TCLIST="7-zip.sh \
aliyun-cli.sh \
ansible.sh \
homebrew.sh \
aws.sh \
aws-sam-cli.sh \
#azcopy.sh \
#azpowershell.sh \
#azure-cli.sh \
#azure-devops-cli.sh \
basic.sh \
bazel.sh \
boost.sh \
build-essential.sh \
clang.sh \
cleanup.sh \
cmake.sh \
complete-snap-setup.sh \
configure-environment.sh \
docker-compose.sh \
docker-moby.sh \
dotnetcore-sdk.sh \
dpkg-config.sh \
erlang.sh \
example.sh \
#firefox.sh \
gcc.sh \
#gfortran.sh \
git.sh \
github-cli.sh \
go.sh \
#google-chrome.sh \
#google-cloud-sdk.sh \
#haskell.sh \
#heroku.sh \
#hhvm.sh \
#homebrew.sh \
#homebrew-validate.sh \
#hosted-tool-cache.sh \
image-magick.sh \
#Install-Toolset.ps1 \
java-tools.sh \
#julia.sh \
kind.sh \
kubernetes-tools.sh \
#leiningen.sh \
#mercurial.sh \
#miniconda.sh \
#mongodb.sh \
#mono.sh \
#mysql.sh \
nodejs.sh \
nvm.sh \
packer.sh \
#phantomjs.sh \
php.sh \
#pollinate.sh \
#postgresql.sh \
#powershellcore.sh \
#preimagedata.sh \
#preparemetadata.sh \
pypy.sh \
python.sh \
#rndgenerator.sh \
ruby.sh \
rust.sh \
#sbt.sh \
#selenium.sh \
#sphinx.sh \
subversion.sh \
swift.sh \
#terraform.sh \
test-toolcache.sh \
validate-disk-space.sh \
Validate-Toolset.ps1 \
#vcpkg.sh \
vercel.sh"

RUN cd ${INSTALL_SCRIPTS}; \
 for s in ${TCLIST}; \
 do \
     set +e; \
     ls ${INSTALL_SCRIPTS}/$s >/dev/null 2>&1; \
     rv=$? ;\
     set -e; \
     if [ ${rv} -eq 0 ];then \
         echo "###${INSTALL_SCRIPTS}/$s"; \
         bash ${INSTALL_SCRIPTS}/validate-disk-space.sh;bash ${INSTALL_SCRIPTS}/$s; \
     else \
         echo "*** not install $s"; \
     fi; \
 done; \
 bash ${INSTALL_SCRIPTS}/cleanup.sh; \
 cat ${METADATA_FILE}
