FROM ubuntu:18.04

COPY . /cicd-s2e-runner

ENV HELPER_SCRIPTS=/cicd-s2e-runner/os/ubuntu/scripts/helpers
ENV INSTALL_SCRIPTS=/cicd-s2e-runner/os/ubuntu/scripts/installers

RUN apt-get update \
 && apt-get install -y lsb wget

RUN  bash /cicd-s2e-runner/os/ubuntu/scripts/base/apt.sh \
 && bash /cicd-s2e-runner/os/ubuntu/scripts/base/limits.sh \
 && bash /cicd-s2e-runner/os/ubuntu/scripts/base/repos.sh

RUN bash ${INSTALL_SCRIPTS}/aliyun-cli.sh
