FROM bettercode/scurl:latest as scurl
FROM centos:7 as runner
COPY --from=scurl /usr/local/bin/scurl /usr/local/bin/scurl
COPY docker /docker
COPY . /s2erunner-src

RUN bash /s2erunner-src/os/centos/scripts/helpers/yum.sh ;\
    bash /s2erunner-src/os/centos/scripts/helpers/basic.sh

RUN bash "/s2erunner-src/os/centos/scripts/installers/c_c++.sh"

RUN bash /s2erunner-src/embed/toolchain/aarch64_be-none-linux-gnu.sh ;\
  bash /s2erunner-src/embed/toolchain/aarch64-none-elf.sh ;\
  bash /s2erunner-src/embed/toolchain/aarch64-none-linux-gnu.sh ;\
  bash /s2erunner-src/embed/toolchain/gcc-arm-none-eabi.sh ;\
  bash /s2erunner-src/embed/toolchain/msp430-gcc.sh ;\
  bash /s2erunner-src/embed/toolchain/andriod.sh ;\
  set +e; ls /opt/embed* ;set -e;



# default config from docker-compose secrets
RUN bash /s2erunner-src/deployments/s2erunner/compose.sh ;\
    bash /s2erunner-src/deployments/s2erunner/.tpl/*.sh ;\
    /bin/cp -rf /s2erunner-src/deployments/s2erunner  /.s2erunner ;\
    ls / /opt/*

RUN bash ${INSTALL_SCRIPTS}/cleanup.sh; \
 touch /error.txt; cat /error.txt; \
 yum clean all; \
 rm -rf /var/cache/yum; \
 rm -rf /root/ts; \
 chmod -R +x /docker/

ENTRYPOINT ["/docker/docker-entrypoint.sh"]

