#!/bin/bash
#author: jimin.huang
#email: jimin.huang@nx-engine.com
set -e
# mark the commit that deploy into env using tag
gitlab project-tag delete --project-id ${CI_PROJECT_ID} --name latest/prd
gitlab project-tag create --project-id ${CI_PROJECT_ID} --ref ${CI_COMMIT_SHA} --tag-name latest/prd

DATETIME=$(date +%Y%m%d-%H%M)
RELEASE_NAME=$(echo release/${DATETIME}-${CI_PROJECT_NAME} | tr _ -)

gitlab project-tag create --project-id ${CI_PROJECT_ID} --ref ${CI_COMMIT_SHA} --tag-name ${RELEASE_NAME}
