#!/bin/bash
#author: jimin.huang
#email: jimin.huang@nx-engine.com
set -e
# mark the commit that deploy into env using tag
set +e
gitlab project-tag delete  --project-id ${CI_PROJECT_ID} --name latest/uat
set -e
gitlab project-tag create --project-id ${CI_PROJECT_ID} --ref ${CI_COMMIT_SHA} --tag-name latest/uat

set +e
source ${SCRIPT_DIR}/jira-util-lib
set -e

