#!/bin/bash
#author: jimin.huang
#email: jimin.huang@nx-engine.com
set -e
THIS_SCRIPT=$(realpath $(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/$(basename ${BASH_SOURCE:-$0}))
SCRIPT_DIR=$(dirname $(realpath ${THIS_SCRIPT}))

# mark the commit that deploy into env using tag
set +e
gitlab project-tag delete  --project-id ${CI_PROJECT_ID} --name latest/dev
gitlab project-tag create --project-id ${CI_PROJECT_ID} --ref ${CI_COMMIT_SHA} --tag-name latest/dev
set -e

set +e
source ${SCRIPT_DIR}/rancher-auto
set -e