#!/bin/bash
#email: jimin.huang@nx-engine.com
#email: jimminh@163.com
set -e
THIS_SCRIPT=$(realpath $(
  cd "$(dirname "${BASH_SOURCE:-$0}")"
  pwd
)/$(basename ${BASH_SOURCE:-$0}))
SCRIPT_DIR=$(dirname $(realpath ${THIS_SCRIPT}))
set +e

function s2iversion_check() {
  #first word in .gitlab-ci.yml as S2I_VERSION
  FIRST_LINE=$(head -n 1 .gitlab-ci.yml)
  YML_S2I_VERSION=$(echo ${FIRST_LINE} | awk '{print $1}' | tr -d '#')

  echo YML_S2I_VERSION=${YML_S2I_VERSION}
  echo RUNNER_S2I_VERSION=${RUNNER_S2I_VERSION}

  case ${YML_S2I_VERSION} in
  "s2i:1")
    echo "please upgrade your .gitlab-ci.yml into s2i:2"
    ;;
  "s2i:2")
    echo "check OK "
    ;;
  *)
    echo "\n\n\n\n"

    ;;
  esac
}

#if cmdtool refer by .gitlab-ci.yml not exist, create on it;
TOOLS="post-all-job
post-artifact-docker-build
post-artifact-docker-build-master
post-artifact-release
post-deploy-dev
post-deploy-prd
post-deploy-test
post-deploy-uat
post-gitlab-auto-merge
post-gitlab-ci-check
post-gitlab-mr-create
post-rollback-test
post-rollback-uat"
for t in ${TOOLS}; do
  which -a $t >/dev/null  2>&1
  RV=$?
  if [[ ${RV} -ne 0 ]];then
    mkdir -p /usr/local/bin
    touch /usr/local/bin/$t
    echo '#!/bin/bash' > /usr/local/bin/$t
    echo 'echo ${0}' > /usr/local/bin/$t
    chmod +x /usr/local/bin/$t
  fi
done

set +e
s2iversion_check
source ${SCRIPT_DIR}/jira-util-lib
if [[ -f ${SCRIPT_DIR}/metric-util-lib ]]; then
  source ${SCRIPT_DIR}/metric-util-lib
fi
set -e
