#!/bin/bash
#email: jimin.huang@nx-engine.com
#email: jimminh@163.com
set -e
THIS_SCRIPT=$(realpath $(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/$(basename ${BASH_SOURCE:-$0}))
SCRIPT_DIR=$(dirname $(realpath ${THIS_SCRIPT}))
export LANG=en_US.UTF-8
set +e
mkdir -p .s2i/
cp ${SCRIPT_DIR}/templates/gitlab/merge-request-template.md .s2i/
echo ${CI_PAGES_URL} >> .s2i/merge-request-template.md
cat  .s2i/merge-request-template.md >> .s2i/merge-request-template.md

gitlab project-merge-request  create  --project-id ${CI_PROJECT_ID} \
 --source-branch ${CI_COMMIT_BRANCH} \
 --target-branch master \
 --title "MR: ${CI_COMMIT_TITLE}" \
 --description @.s2i/merge-request-template.md \
 --labels ${GITLAB_USER_LOGIN} \
 --assignee-id ${GITLAB_USER_ID} \

RV=$?
if [[  ! -f .s2i/request-note.txt ]];then
echo "Update by @${GITLAB_USER_LOGIN} " > .s2i/request-note.txt
echo "镜像地址: " >> .s2i/request-note.txt
cat .s2i.*img.txt >> .s2i/request-note.txt
fi


set -e

if [[ ${RV=$?} -ne 0 ]];then
    gitlab  project-merge-request  list \
    --project-id ${CI_PROJECT_ID}   \
    --source-branch ${CI_COMMIT_BRANCH} \
    --target-branch master  | head -n 1 | awk '{print $2}' > $(echo .mr-iid.${CI_PROJECT_ID}.${CI_COMMIT_BRANCH} | tr / -)


    gitlab project-merge-request-note create \
    --project-id ${CI_PROJECT_ID}  \
    --mr-iid $(head -n 1  $(echo .mr-iid.${CI_PROJECT_ID}.${CI_COMMIT_BRANCH} | tr / -)) \
    --body @s2i.request-note.txt \

fi

