#!/bin/bash
#email: jimin.huang@nx-engine.com
#email: jimminh@163.com
#args TPL_FILE, where your gitlab mr template file is
set -e
THIS_SCRIPT=$(realpath $(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/$(basename ${BASH_SOURCE:-$0}))
SCRIPT_DIR=$(dirname $(realpath ${THIS_SCRIPT}))
export LANG=en_US.UTF-8

set +e
if [[ -f ${SCRIPT_DIR}/metric-util-lib ]];then
  source ${SCRIPT_DIR}/metric-util-lib
fi
set -e

