#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# author: huangjimin
# e-mail: jimin.huang@nx-engine.com
# e-mail: jimminh@163.com

# Import directives
import os
import logging
import subprocess
import yaml
import requests

i2e_ctrl = {
    "dry_run": False
}
def do_shell_exe(cmd, env_append={}):
    env_new = os.environ
    for k in env_append:
        env_new[k] = env_append[k]
    if i2e_ctrl["dry_run"]:
        print(cmd)
    else:
        p = subprocess.Popen(cmd, shell=True, bufsize=2048, stdin=subprocess.PIPE, env=env_new)
        p.wait()
        if p.returncode == 0:
            pass
    return

#curl -X GET --header 'Accept: application/json' 'https://harbor.nx-engine.com/api/repositories/icev3%2Fcpsp-integration-service/tags?detail=false&api_key=repositories'
def do_get_harbor_img_latest(docker_name, docker_ns="library", docker_repo="harbor.nx-engine.com"):
    if docker_ns == "library":
        docker_ns = os.environ.get("DOCKER_NS", 'library')
    url = "http://%s/api/repositories/%s/%s/tags?detail=false" %(docker_repo, docker_ns, docker_name)
    try:
        resp = requests.get(url).json()
    except Exception:
        print("sss")
        pass
    if resp:
        tag = resp[-1] ["name"]
    else:
        tag = "latest"
    img = "%s/%s/%s:%s" % (docker_repo, docker_ns, docker_name, tag)
    return img
def do_k8s_svc_list(file, options, action_args):
    log.info("do_svc_list")
    with open(file) as f:
        y = yaml.load(f, Loader=yaml.SafeLoader)
    if len(action_args) > 0:
        for a in action_args:
            if a in y.keys():
                print(a)
            else:
                log.warning("%s ,not found in file", a)
            # log.info(y.get(k))
    else:
        for k in y.keys():
            print(k)
            # log.info(y.get(k))
    return

def do_k8s_ns_import(file, options, action_args):
    log.info("do_k8s_ns_import")
    k8s_script_dir = "%s" % (os.path.dirname(os.path.realpath(__file__)))
    k8s_app_import = "k8s-app-import"
    docker_repo = os.environ.get("DOCKER_REPO", 'harbor.nx-engine.com')
    docker_ns = os.environ.get("DOCKER_NS", 'default')

    with open(file) as f:
        y = yaml.load(f, Loader=yaml.SafeLoader)

    docker_repo = y.get("global")["src"]["docker"]["repo"]
    docker_ns = y.get("global")["src"]["docker"]["ns"]

    k8s_dst_ns = y.get("global")["dst"]["k8s"]["ns"]
    if options.src_kubeconfig:
        src_kubeconfig = options.src_kubeconfig
    if options.dst_kubeconfig:
        dst_kubeconfig = options.dst_kubeconfig

    if options.k8s_src_ns:
        k8s_src_ns = options.k8s_src_ns
    if options.k8s_dst_ns:
        k8s_dst_ns = options.k8s_dst_ns

    svcs = []
    if len(action_args) >= 1:
        for a in action_args[0:]:
            if a in y.keys():
                svcs.append(a)
    else:
        svcs = list(y.keys())

    if svcs:
        svcs.sort()
    else:
        return
    for a in svcs:
        if a == "global":
            continue
        print("")
        app_img = y.get(a)[a]["image"]
        app_name = a
        app_ports = ",".join(str(p) for p in y.get(a)[a]["service"]["ports"])
        app_autocd = "1"
        app_domain_internal = y.get("global")["dst"]["k8s"]["ingress"]["internal"]["domain"]
        app_domain_public = y.get("global")["dst"]["k8s"]["ingress"]["public"]["domain"]

        if i2e_ctrl["dry_run"]:
            app_autocd="0"

        if app_img is None:
            log.info("%s Latest img", a)
            raise ValueError("docker image None for %" % a)
        else:
            log.info("%s Manual img", a)

        cmd = "'%s/%s' '%s' '%s' '%s' '%s' '%s' '%s' '%s'  " % (k8s_script_dir, k8s_app_import,
                           app_img, app_name, k8s_dst_ns, app_ports, app_autocd,
                                                app_domain_internal, app_domain_public)
        do_shell_exe(cmd)
    return
def do_k8s_ns_export(file, options, action_args):
    log.info("do_k8s_ns_export")
    k8s_script_dir = "%s" % (os.path.dirname(os.path.realpath(__file__)))
    cmd_tool = "k8s-ns-export"

    if file:
        with open(file) as f:
            y = yaml.load(f, Loader=yaml.SafeLoader)

        src_kubeconfig = y.get("global")["src"]["k8s"]["kubeconfig"]
        dst_kubeconfig = y.get("global")["dst"]["k8s"]["kubeconfig"]
        k8s_src_ns = y.get("global")["src"]["k8s"]["ns"]
        k8s_dst_ns = y.get("global")["dst"]["k8s"]["ns"]
    if options.src_kubeconfig:
        src_kubeconfig = options.src_kubeconfig
    else:
        src_kubeconfig = "%s/.kube/config" % os.environ['HOME']
    if options.dst_kubeconfig:
        dst_kubeconfig = options.dst_kubeconfig

    if options.k8s_src_ns:
        k8s_src_ns = options.k8s_src_ns
    if options.k8s_dst_ns:
        k8s_dst_ns = options.k8s_dst_ns
    if options.outdir:
        outdir = options.outdir
    else:
        outdir = os.path.realpath("./o-%s" % k8s_src_ns)

        if i2e_ctrl["dry_run"]:
            app_autocd="0"
        env_append = {}
        env_append['KUBECONFIG'] = src_kubeconfig

        cmd = "'%s/%s' '%s' '%s' " % (k8s_script_dir, cmd_tool, k8s_src_ns, outdir)
        do_shell_exe(cmd, env_append)
    return
def do_docker_ns_mirror(file, options, action_args):
    log.info("do_docker_ns_mirror")
    log.info("do_docker_ns_mirror")
    script_dir = "%s" % (os.path.dirname(os.path.realpath(__file__)))
    cmd_tool = "docker-ns-mirror"
    docker_dst_repo = os.environ.get("DOCKER_DST_REPO", 'harbor.nx-engine.com')
    docker_dst_ns = os.environ.get("DOCKER_DST_NS", 'default')

    with open(file) as f:
        y = yaml.load(f, Loader=yaml.SafeLoader)

    docker_dst_repo = y.get("global")["dst"]["docker"]["repo"]
    docker_dst_ns = y.get("global")["dst"]["docker"]["ns"]

    k8s_dst_ns = y.get("global")["dst"]["k8s"]["ns"]
    if options.docker_dst_repo:
        docker_dst_repo = options.docker_dst_repo
    if options.docker_dst_ns:
        docker_dst_ns = options.docker_dst_ns


    svcs = []
    if len(action_args) >= 1:
        for a in action_args[0:]:
            if a in y.keys():
                svcs.append(a)
    else:
        svcs = list(y.keys())

    if svcs:
        svcs.sort()
    else:
        return
    for a in svcs:
        if a == "global":
            continue
        print("")
        app_img = y.get(a)[a]["image"]
        app_name = a

        if i2e_ctrl["dry_run"]:
            app_autocd="0"

        if app_img is None:
            log.info("%s Latest img", a)
            raise   ValueError("app_img None for %s" % a)
        else:
            log.info("%s Manual img", a)

        app_img_x = app_img.split('/')[-1].split(':')[0]
        app_img_y = app_img.split('/')[-1].split(':')[-1]
        if app_img_x == app_img_y:
            old_tag = "latest"
        else:
            old_tag = app_img_y
        if options.docker_retag_prefix:
            new_tag = options.docker_retag_prefix + old_tag
        else:
            new_tag = old_tag
        cmd = "'%s/%s' '%s' '%s' '%s' '%s' '%s' '%s'  " % (script_dir, cmd_tool,
                           app_img, app_name, docker_dst_repo, docker_dst_ns, old_tag, new_tag)
        do_shell_exe(cmd)
    return
actions_tbl = {
        "docker-ns-mirror": do_docker_ns_mirror,
        "k8s-svc-list": do_k8s_svc_list,
        "k8s-ns-import": do_k8s_ns_import,
        "k8s-ns-export": do_k8s_ns_export
    }

def action_dispatcher(file, options, action, action_args):
    log.info("action: %s, action_args: %s", action, action_args)
    if action in actions_tbl.keys():
        actions_tbl[action](file, options, action_args)
    else:
        log.warning("not support action %s", action)
    return

# Logging
def logger_init():
    """Initialize logger instance."""
    log = logging.getLogger("S2E")
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(
        # logging.Formatter("[%(asctime)s %(name)s %(levelname)s] %(message)s"))
        logging.Formatter("[%(name)s %(levelname)s] %(message)s"))
    log.addHandler(console_handler)
    log.setLevel(20)
    return log

def command_line():
    """
    help doc
    """
    from optparse import OptionParser
    usage_example = """
    %prog [OPTIONS] ACTION
    
    Note: value in OPTIONS are higher priority then images.yaml
    ### maintain k8s deploy
    # export all apps to images.yaml from k8s namespaces
    %prog -o images-dev.yaml --src-kubeconfig /root/dev.config --k8s-src-ns default k8s-ns-export 
     
    # deploy all apps into k8s ns
    %prog -i images.yaml k8s-ns-import
    
    # only deploy nginx into k8s in images.yaml
    %prog -i images.yaml k8s-ns-import nginx
    
    ## maintain docker img
    ## pull all docker image, then push into ${docker_dst_repo}/${docker_dst_ns}
    %prog -i images.yaml --docker-dst-repo=docker.io --docker-dst-ns=bettercode docker-ns-mirror 
     
    ##  pull all docker image, retag whith prefix, then push into repo
    %prog -i images.yaml --docker-rereg=prd- --docker-dst-repo=docker.io --docker-dst-ns=bettercode docker-ns-mirror 
       
    """

    usage = "usage: \n    %prog -i [images.yaml] " + ("%s" % list(actions_tbl.keys())) + " [args ...]" + usage_example

    parser = OptionParser(usage=usage)
    parser.add_option("-i", "--image", action="store",
                      dest="file",
                      help="image file")
    parser.add_option("-o", "--outdir", action="store",
                      dest="outdir",
                      help="export images.yaml to dir")
    parser.add_option("--k8s-src-ns", action="store",
                      dest="k8s_src_ns",
                      help="get img from namespace")
    parser.add_option("--k8s-dst-ns", action="store",
                      dest="k8s_dst_ns",
                      help="deploy into namespace")
    parser.add_option("--src-kubeconfig", action="store",
                      dest="src_kubeconfig",
                      help="the src k8s kubeconfig")
    parser.add_option("--dst-kubeconfig", action="store",
                      dest="dst_kubeconfig",
                      help="the dst k8s kubeconfig")
    parser.add_option("--docker-dst-repo", action="store",
                      dest="docker_dst_repo",
                      help="mirror into docker repo")
    parser.add_option("--docker-dst-ns", action="store",
                      dest="docker_dst_ns",
                      help="mirror into docker namespace")
    parser.add_option("--docker-retag-prefix", action="store",
                      dest="docker_retag_prefix",
                      help="mirror into docker namespace")
    parser.add_option("--force", action="store_true",
                      dest="force",
                      help="force redeploy,not just update img")
    parser.add_option("-d", "--dry-run", action="store_true",
                      dest="dry_run",
                      help="simulate an run")
    parser.add_option("-v", "--verbose", action="store_true",
                      dest="verbose", help="Verbose mode")
    (options, args) = parser.parse_args()
    if options.verbose:
        log.setLevel(10)
    if options.dry_run:
        i2e_ctrl["dry_run"] = True
    # file = os.path.realpath("./images.yaml")
    file = None
    if options.file:
        file = os.path.realpath(options.file)

    if len(args) < 1:
        action = 'help'  # default list service
        action_args = []
        parser.print_help()
    elif len(args) == 1:
        action = args[0]
        action_args = []
    else:
        action = args[0]
        action_args = args[1:]
    if file:
        log.info("file: %s", file)
    log.debug('Start monitoring deployment into kubernetes')
    action_dispatcher(file, options, action, action_args)

log = logger_init()

if __name__ == '__main__':
    command_line()
