#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# author jimin.huang@nx-engine.com

# Import directives
import os
import logging
import subprocess
import yaml
import requests

i2e_ctrl = {
    "dry_run": False
}
def do_shell_exe(cmd):
    if i2e_ctrl["dry_run"]:
        print(cmd)
    else:
        p = subprocess.Popen(cmd, shell=True, bufsize=2048, stdin=subprocess.PIPE)
        p.wait()
        if p.returncode == 0:
            pass
    return

#curl -X GET --header 'Accept: application/json' 'https://harbor.nx-engine.com/api/repositories/icev3%2Fcpsp-integration-service/tags?detail=false&api_key=repositories'
def do_get_harbor_img_latest(docker_name, docker_ns="library", docker_repo="harbor.nx-engine.com"):
    if docker_ns == "library":
        docker_ns = os.environ.get("DOCKER_NS", 'library')
    url = "http://%s/api/repositories/%s/%s/tags?detail=false" %(docker_repo, docker_ns, docker_name)
    try:
        resp = requests.get(url).json()
    except Exception:
        print("sss")
        pass
    if resp:
        tag = resp[-1] ["name"]
    else:
        tag = "latest"
    img = "%s/%s/%s:%s" % (docker_repo, docker_ns, docker_name, tag)
    return img
def do_svc_list(file, action_args):
    log.info("do_svc_list")
    with open(file) as f:
        y = yaml.load(f, Loader=yaml.SafeLoader)
    if len(action_args) > 0:
        for a in action_args:
            if a in y.keys():
                print(a)
            else:
                log.warning("%s ,not found in file", a)
            # log.info(y.get(k))
    else:
        for k in y.keys():
            print(k)
            # log.info(y.get(k))
    return

def do_svc_deploy(file, action_args):
    log.info("do_svc_deploy")
    k8s_script_dir = "%s" % (os.path.dirname(os.path.realpath(__file__)))
    k8s_app_import = "k8s-app-import"
    k8s_ns = action_args[0]
    docker_repo = os.environ.get("DOCKER_REPO", 'harbor.nx-engine.com')
    docker_ns = os.environ.get("DOCKER_NS", 'icev3')

    with open(file) as f:
        y = yaml.load(f, Loader=yaml.SafeLoader)

    docker_repo = y.get("global")["docker"]["repo"]
    docker_ns = y.get("global")["docker"]["ns"]

    svcs = []
    if len(action_args) > 1:
        for a in action_args[1:]:
            if a in y.keys():
                svcs.append(a)
    else:
        svcs = list(y.keys())

    svcs.sort()
    for a in svcs:
        if a == "global":
            continue
        print("")
        app_img = y.get(a)[a]["image"]
        app_name = a
        app_ports = ",".join(str(p) for p in y.get(a)[a]["service"]["ports"])
        app_autocd = "1"
        app_domain_internal = y.get("global")["ingress"]["internal"]["domain"]
        app_domain_public = y.get("global")["ingress"]["public"]["domain"]

        if i2e_ctrl["dry_run"]:
            app_autocd="0"

        if app_img is None:
            app_img = do_get_harbor_img_latest(app_name, docker_ns, docker_repo)
            log.info("%s Latest img", a)
        else:
            log.info("%s Manual img", a)

        cmd = "%s/%s %s %s %s '%s' %s %s %s  " % (k8s_script_dir, k8s_app_import,
                           app_img, app_name, k8s_ns, app_ports, app_autocd,
                                                app_domain_internal, app_domain_public)
        do_shell_exe(cmd)
    return
def do_ns_deploy(file, action_args):
    log.info("do_ns_deploy")
    pass

actions_tbl = {
    "svclist": do_svc_list,
    "svcdeploy": do_svc_deploy,
    "nsdeploy": do_ns_deploy
}
def action_dispatcher(file, action, action_args):
    log.info("action: %s, action_args: %s", action, action_args)
    if action in actions_tbl.keys():
        actions_tbl[action](file, action_args)
    else:
        log.warning("not support action %s", action)
    return

# Logging
def logger_init():
    """Initialize logger instance."""
    log = logging.getLogger("S2E")
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(
        # logging.Formatter("[%(asctime)s %(name)s %(levelname)s] %(message)s"))
        logging.Formatter("[%(name)s %(levelname)s] %(message)s"))
    log.addHandler(console_handler)
    log.setLevel(20)
    return log

def command_line():
    """
    help doc
    """
    from optparse import OptionParser
    usage = "usage: %prog -i [images.yaml] " + ("%s" % list(actions_tbl.keys())) + " [args ...]"

    parser = OptionParser(usage=usage)
    parser.add_option("-i", "--image", action="store",
                      dest="file",
                      help="image file")
    parser.add_option("--namespace", action="store",
                      dest="namespace",
                      help="deploy into namespace")
    parser.add_option("--kubeconfig", action="store",
                      dest="kubeconfig",
                      help="the k8s kubeconfig")
    parser.add_option("--force", action="store_true",
                      dest="force",
                      help="force redeploy,not just update img")
    parser.add_option("-d", "--dry-run", action="store_true",
                      dest="dry_run",
                      help="simulate an run")
    parser.add_option("-v", "--verbose", action="store_true",
                      dest="verbose", help="Verbose mode")
    (options, args) = parser.parse_args()
    if options.verbose:
        log.setLevel(10)
    if options.dry_run:
        i2e_ctrl["dry_run"] = True
    file = os.path.realpath("./images.yaml")
    if options.file:
        file = os.path.realpath(options.file)

    if len(args) < 1:
        action = 'help'  # default list service
        action_args = []
        parser.print_help()
    elif len(args) == 1:
        action = args[0]
        action_args = []
    else:
        action = args[0]
        action_args = args[1:]

    log.info("file: %s", file)
    log.debug('Start monitoring deployment into kubernetes')
    action_dispatcher(file, action, action_args)


log = logger_init()

if __name__ == '__main__':
    command_line()
