#!/bin/bash
#author: jimin.huang
#email: jimin.huang@nx-engine.com
set -e
echo "$0"


# save job env to file, let featbeats proccess
function gitlab-job-metric-savefile() {
  CI_JOB_EXIT_RV=\$?
  if [[ -z ${GITLAB_JOB_METRIC_DIR} ]];then
    GITLAB_JOB_METRIC_DIR=/var/log/gitlab-job-metric/$(date +%Y%m)
    mkdir -p ${GITLAB_JOB_METRIC_DIR}
  fi
  METRIC_DIR=${GITLAB_JOB_METRIC_DIR}/${CI_PROJECT_ID}/${CI_PIPELINE_ID}/${CI_JOB_ID}
  mkdir -p ${METRIC_DIR}
  export CI_JOB_EXIT_RV
  export CI_JOB_TIMESTAMP_END=$(date)
  #使用两个##将环境变量连接成一行
  export |egrep -v LS_COLORS | perl -ne 'chomp;s/^declare -x //g;print "$_##"' >> /${METRIC_DIR}/env.txt
  echo "" >> /${METRIC_DIR}/env.txt
}
gitlab-job-metric-savefile