#!/bin/bash
#author: jimin.huang
#email: jimin.huang@benload.com
set -e
THIS_SCRIPT=$(realpath $(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/$(basename ${BASH_SOURCE:-$0}))
SCRIPT_DIR=$(dirname $(realpath ${THIS_SCRIPT}))
# mark the commit that deploy into env using tag
set +e
gitlab project-tag delete --project-id ${CI_PROJECT_ID} --name latest/prd
set -e
gitlab project-tag create --project-id ${CI_PROJECT_ID} --ref ${CI_COMMIT_SHA} --tag-name latest/prd


touch s2ectl.env.ok.${CI_JOB_NAME}
# 本shell 执行完，说明改job 执行完成；
