#!/bin/bash
#email: jimin.huang@nx-engine.com
#email: jimminh@163.com
set -e
THIS_SCRIPT=$(realpath $(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/$(basename ${BASH_SOURCE:-$0}))
SCRIPT_DIR=$(dirname $(realpath ${THIS_SCRIPT}))

set +e
source ${SCRIPT_DIR}/jira-util-lib
${SCRIPT_DIR}/metric-util-lib
set -e

touch s2ectl.env.ok.${CI_JOB_NAME}
# 本shell 执行完，说明改job 执行完成；