stages:
  - s3
s3-deploy-to-env1:
  stage: s3
  script:
     - echo s3-deploy-to-env1 $CI_JOB_NAME
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/
s3-deploy-to-env2:
  stage: s3
  when: manual
  script:
     - echo s3-deploy-to-env2 $CI_JOB_NAME
     - echo VAR="${VAR}"
     - export VAR="${VAR} s3"
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/
s3-deploy-to-env3:
  stage: s3
  when: manual
  script:
     - echo s3-deploy-to-env3 $CI_JOB_NAME
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/