#!/bin/bash
#author: jimin.huang
#email: jimin.huang@benload.com
set -e
THIS_SCRIPT=$(realpath $(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/$(basename ${BASH_SOURCE:-$0}))
SCRIPT_DIR=$(dirname $(realpath ${THIS_SCRIPT}))

set +e
${SCRIPT_DIR}/metric-util-lib
set -e