stages:
  - s1
s1:
  stage: s1
  script:
     - echo s1
     - echo VAR="${VAR}"
     - export VAR="s1"
     - ./s2e/s2i .
  only:
    - master
    - /^rc.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^feature.*$/ 
  except:
    - /^dev.*$/
